### ISSUE TITLE
[Feature/Idea]: Add .exe Microsoft.edge packages

### ISSUE THREAD

**Issue by lychichem** [vedantmgoyal9/winget-pkgs-automation#1203]
### What would you like to see changed/added?

Related issue: microsoft/winget-pkgs#99536
To get the offline .exe package download link:
```
Out-File $env:temp\edge.txt
foreach ($channel in "stable", "beta", "dev", "canary")
{
    foreach ($platform in "x64", "x86")
    {
        $version = (Invoke-RestMethod -Uri https://msedge.api.cdp.microsoft.com/api/v1.1/contents/Browser/namespaces/Default/names/msedge-$channel-win-$platform/versions/latest?action=select -Method POST -Body targetingAttributes).ContentId.Version
        $url =  Invoke-RestMethod -Uri "https://msedge.api.cdp.microsoft.com/api/v1.1/internal/contents/Browser/namespaces/Default/names/msedge-$channel-win-$platform/versions/$version/files?action=GenerateDownloadInfo&foregroundPriority=true" -Method POST
        $title = "Microsoft Edge $channel win $platform" | Out-File $env:temp\edge.txt -Append
        ($url | sort SizeInBytes | Select-Object FileId -Last 1).FileId | Out-File $env:temp\edge.txt -Append
        ($url | sort SizeInBytes | Select-Object url -Last 1).url | Out-File $env:temp\edge.txt -Append
        "" | Out-File $env:temp\edge.txt -Append
    }
}
notepad.exe $env:temp\edge.txt
```

The download link for current edge stable/beta/dev/can will be outputed into a txt file. Code written by a Kafan (bbs.kafan.cn) user cloudz (not me).

I tested on my locale machine. Package renaming will be needed. And install switch should be `--msedge --channel=xxx --system-level --verbose-logging` for Edge and `--msedgewebview --system-level --verbose-logging` for webview 2. Admin priviledge will be needed to run the installer.

**Comment by vedantmgoyal9** [comment]
I get 404, 405, and 415 HTTP error codes every time. cc @SpecterShell @lychichem

**Comment by lychichem** [comment]
> I get 404, 405, and 415 HTTP error codes every time. cc @SpecterShell @lychichem

Now this script cannot work anymore. I use this site (https://chrome.noki.eu.org/edge) now. You may analyse the code of this site.

**Comment by vedantmgoyal9** [comment]
@SpecterShell can you please find APIs for Edge, like you did for Chrome and Brave?

**Comment by SpecterShell** [comment]
> @SpecterShell can you please find APIs for Edge, like you did for Chrome and Brave?

Edge has its own API implementation different from those of other browsers. I will look into it in my spare time.

Edge uses delta upgrade installers in updating. I will see if I can get the installers from first-time installation.

**Comment by SpecterShell** [comment]
Maybe impossible.
The (dynamic) URL of the latest installer has a form like this:
http://msedge.f.tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/d3350327-c35b-4a84-b333-2ab428af95e6?P1=1691996069&P2=404&P3=2&P4=PB4qEYW4pYbXCmgjerQqQX2a746UIP9vhvOGNhI07L2VwpnirnFkxBAiYFLwGYKh%2fl%2bvZooXubZSGO2M8U7GkA%3d%3d
Where the argument `P1` is a timestamp and the argument `P4` looks like a hashing of previous arguments, which means this is a dynamic link rather than a stable one. If this link becomes inaccessible later after I comment, we won't be able to get the link from downloading source or updating source.

**Comment by vedantmgoyal9** [comment]
I think there is no need for adding .exe installer URLs in automation, as there isn't one in winget-pkgs, and since there are no official .exe offline installers' URLs that can be added to winget-pkgs repo (winget only accepts official download URLs, and Edge is itself a Microsoft product), I'm closing this issue. In the future, if there will be one, I'll add it to automation.

**Comment by BrandonWanHuanSheng** [comment]
> Maybe impossible.
> The (dynamic) URL of the latest installer has a form like this:
> http://msedge.f.tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/d3350327-c35b-4a84-b333-2ab428af95e6?P1=1691996069&P2=404&P3=2&P4=PB4qEYW4pYbXCmgjerQqQX2a746UIP9vhvOGNhI07L2VwpnirnFkxBAiYFLwGYKh%2fl%2bvZooXubZSGO2M8U7GkA%3d%3d
> Where the argument `P1` is a timestamp and the argument `P4` looks like a hashing of previous arguments, which means this is a dynamic link rather than a stable one. If this link becomes inaccessible later after I comment, we won't be able to get the link from downloading source or updating source.

That one we use as windows 10 or Windows 11 setup as dynamic update, Features Pack, Language Pack or Optional Feature. But the link is invalid afterwards.
