### ISSUE TITLE
Bug: Call YamlCreate.ps1 script with Parameters

### ISSUE THREAD

**Issue by vedantmgoyal9** [vedantmgoyal9/winget-pkgs-automation#15]
**Describe the bug**
Calling YamlCreate.ps1 script with parameters does not work properly. The way I tried to call the script can be seen in these commits (693189dcdf464a3482f2c24e631ec278748a3180, 5abe8c2009eb39623cb762218d2117bcfe8ff88b) and the result can be in the logs of workflow runs #47, #48, #49.

**Expected behavior**
YamlCreate should get parameters and does not prompt for select mode, package identifier, etc...

**Additional context**

**Comment by vedantmgoyal2009** [comment]
@Trenly Please help me to fix this small thing.

**Comment by Trenly** [comment]
Try using Invoke-Command and including the parameter names https://www.roelvanlisdonk.nl/2010/03/25/how-to-call-a-powershell-script-with-named-parameters-from-a-powershell-ps1-script/

```
Invoke-Command $(“./path/YamlCreate.ps1” -PackageName $Package.name -PackageVersion $Version -Mode 2 -Urls $Urls)
```

**Comment by Trenly** [comment]
Didn’t work?

**Comment by vedantmgoyal2009** [comment]
edit 2 worked... Thanks for your help.

**Comment by vedantmgoyal2009** [comment]
Is `NuGet` necessary?
![image](https://user-images.githubusercontent.com/83997633/135702542-72fe4169-7147-40f6-996a-292cba0db470.png)

**Comment by Trenly** [comment]
> Is `NuGet` necessary?
> ![image](https://user-images.githubusercontent.com/83997633/135702542-72fe4169-7147-40f6-996a-292cba0db470.png)

Yes; Unless you install powershell-yaml manually. If you don’t have the NuGet provider it won’t be able to download powershell-yaml

**Comment by vedantmgoyal2009** [comment]
@Trenly There is another problem. Commit 0dd07006ac7892f7a389e74eea212a27bfdad08f worked perfectly but YamlCreate could not detect previous version. I think as YamlCreate uses $psscriptroot variable so we need to find another way or make some changes while calling the script.

Workflow log of commit 0dd07006ac7892f7a389e74eea212a27bfdad08f: https://github.com/vedantmgoyal2009/winget-pkgs-automation/runs/3774285727?check_suite_focus=true#step:3:165

**Comment by Trenly** [comment]
I think `$PWD.path` would work instead, as long as you `Set-Location` to `./winget-pkgs`

**Comment by vedantmgoyal2009** [comment]
@Trenly The whole issue is caused by https://github.com/vedantmgoyal2009/winget-pkgs-automation/blob/704e29888d2760b764f3a3ef1c1efb3bb9a0e6bb/automation.ps1#L19 which does not copy the unattended version of the script.

I came to know this, is because I finally gave up and thought to remove unused parts (keypress menus, and new & update locale modes, etc. which is not a good idea) in the script. I did a workflow run and it was still asking for the mode prompt which I had removed. After that, I added a `Compare-Object` and did another run which made me confirm that the script does not get copied. Also, the current version of YamlCreate in the winget-pkgs repo is 1.1.6 which does not respect any parameters passed to it and hence, I was thinking that there is a problem in calling the script with parameters. 

Can you tell why does the `Copy-Item` doesn't copy the file? Am I missing something or is it because of the folder permissions given to the user on the GitHub Actions VM?
