### ISSUE TITLE
[Bug]: Butterfly won't be updated

### ISSUE THREAD

**Issue by CodeDoctorDE** [vedantmgoyal9/winget-pkgs-automation#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I don't know why it does not update. I released an 1.2.1, an 1.3.0-alpha.0 and an 1.3.0-alpha.0

**Comment by vedantmgoyal9** [comment]
It is because the automation is hitting API rate limits, but there is good news. I'm working on a GitHub Action about which I had told you earlier, and it will be ready in the next few hours. I understand that you and other publishers are facing inconvenience since you all are dependent on my automation. Once it is ready, I will create the pull request to add the action on your repository.
