### ISSUE TITLE
[Bug]: Oxen.Session not getting updated?

### ISSUE THREAD

**Issue by OfficialEsco** [vedantmgoyal9/winget-pkgs-automation#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I submitted 1.7.9 2022-03-31 and 1.8.4 got released 2022-04-26
However the json says last checked version is 1.7.7

https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/3732eb40105fbe85e7ac1e822d43c66f5311a114/winget-pkgs-automation/packages/o/oxen.session.json#L18

**Comment by vedantmgoyal9** [comment]
I performed some tests yesterday and it seems that automation is much more broken than it seems. Mainly due to rate limits, but there is some error in YamlCreate.ps1 too.

If you take a look at https://github.com/vedantmgoyal2009/vedantmgoyal2009/runs/6194736074?check_suite_focus=true, you'll notice that version is constant to 11.0.11.9

**Comment by OfficialEsco** [comment]
Pretty sure i've noticed this for a long time as i've seen the Automation pick up some packages then not release the next version so its still in my RSS feed, also its gotten slower, so probably hitting a few rate limits yeah
