### ISSUE TITLE
[New Package]: Chocolatey.ChocolateyGUI

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#488]
### List the PackageIdentifier of the package to be added to automation

Chocolatey.ChocolateyGUI

### Details about the application

https://github.com/chocolatey/ChocolateyGUI/releases

**Comment by vedantmgoyal9** [comment]
@SpecterShell I think for GitHub packages, we can request the package maintainers to automate the publishing of manifests for their package. If they deny it, then we can add the package here. I know it will be time-taking but it will be more efficient, since with too many packages the automation will be more likely to hit API rate limits which will delay in updating version.

Currently, we have about 14 packages which are automated [using my action](https://github.com/vedantmgoyal2009/vedantmgoyal2009/network/dependents?package_id=UGFja2FnZS0zMDc5MjM2ODE2) and some by wingetcreate or other methods.

**Comment by vedantmgoyal9** [comment]
* https://github.com/chocolatey/ChocolateyGUI/issues/943

**Comment by vedantmgoyal9** [comment]
Added to https://docs.google.com/spreadsheets/d/1dnTRsRI8JdTyHibbBy8b1-Odd1gHJRjScm_KWUQ-jHk/edit?usp=sharing
