### ISSUE TITLE
[Bug]: Sigil-Ebook.Sigil not getting updated

### ISSUE THREAD

**Issue by OfficialEsco** [vedantmgoyal9/winget-pkgs-automation#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Project Name

WinGet Automation

### What happened?

[sigil-ebook.sigil.json](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/s/sigil-ebook.sigil.json) appears not to be working correctly

edit:
>I don't know all the particulars, but it it looks to me that the issue might be the version reference in that json. The lookbehind expression seems to be expecting a 'v' in the version/tag which is trimmed off later.
>
>"VersionRegex": "(?<=v)[0-9.]+"
>
>Sigil tags don't start with a 'v'.
>
>I could be all wet about how the automation checks version numbers, though. Thanks for looking into it! I'm sure it will get sorted.
>
>_Originally posted by @dougmassay in https://github.com/Sigil-Ebook/Sigil/issues/635#issuecomment-1141368119_

**Comment by vedantmgoyal9** [comment]
When you have last updated Sigil (https://github.com/microsoft/winget-pkgs/pull/54617) 2 months ago, you have entered 32-bit URLs in both x86 and x64 archs. If we do `Select-Unique`, the count of URLs will be 1.

Whereas, the automation finds two unique installer URLs, so it does not create a pull request to update the package since the number of installer URLs are not equal.

The JSON has now been updated in the run 1822 because it [found an existing pull request](https://github.com/vedantmgoyal2009/vedantmgoyal2009/runs/6659666372?check_suite_focus=true#step:5:1334) for the version 1.9.10.

**Comment by OfficialEsco** [comment]
yeeeeeah i noticed the url issue yesterday, url fix pr up now

**Comment by vedantmgoyal9** [comment]
the package will be updated from the developer side now ;)
