### ISSUE TITLE
[New Package]: Tencent.TencentMeetingRooms

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal9/winget-pkgs-automation#679]
### List the PackageIdentifier of the package to be added to automation

Tencent.TencentMeetingRooms

### Details about the application

https://meeting.tencent.com/web-service/query-download-info?q=[{%22package-type%22:%22rooms%22,%22channel%22:%221410000391%22,%22platform%22:%22windows%22}]&nonce=AAAAAAAAAAAAAAAA

PackageVersion: $Response.'info-list'[0].version
InstallerUrl: $Response.'info-list'[0].url
ReleaseDate: $Response.'info-list'[0].'sub-date'

**Comment by vedantmgoyal9** [comment]
@SpecterShell I've been lazy on adding more packages to the automation since I was going through GitHub packages, creating PRs on repositories implementing winget-releaser in their release CI, some of them have been accepted. Moving them to winget-releaser action has freed up space for more packages to be added; the automation was hitting GitHub API rate limits previously.

I'm back now, adding more packages, especially non-GitHub ones, so you can open more issues and PRs like before to add them to automation.
