### ISSUE TITLE
[New Package]: Mozilla Firefox

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#880]
### List the PackageIdentifier of the package to be added to automation

Mozilla.Firefox

### Details about the application

This request is for regular Mozilla Firefox. There's already a discussion for Mozilla Firefox Nightly, although it's not in the latest version right now:
https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/17

**Comment by ppvnf** [comment]
https://github.com/microsoft/winget-pkgs/pull/82512. I don't know if it is automated already

**Comment by vedantmgoyal9** [comment]
I already have it in the works, but will commit the changes after all installers are added to WinGet (a PR is already open for it).

* https://github.com/microsoft/winget-pkgs/pull/60151

There's a PR in progress for beta, which cannot pass due to a bug in pipelines, which is to be fixed by MS team. After the bug-fix, PRs will be opened for adding all installers to every Firefox pacakge. BTW, I'm merging this request with Nightly.

* https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/17
