### ISSUE TITLE
[New Package]: Bitwarden

### ISSUE THREAD

**Issue by ppvnf** [vedantmgoyal9/winget-pkgs-automation#908]
### List the PackageIdentifier of the package to be added to automation

Bitwarden.Bitwarden

### Details about the application

https://community.bitwarden.com/t/please-use-winget-releaser-automatically-updates-winget-version/45263
https://github.com/microsoft/winget-pkgs/issues/81125
I'm not sure they are gonna implement it since I had to make the feature request outside Github

**Please upvote my post [there](https://community.bitwarden.com/t/please-use-winget-releaser-automatically-updates-winget-version/45263)**

**Comment by vedantmgoyal9** [comment]
You can create a feature request at https://github.com/bitwarden/clients/issues, so it may get the attention of the team who manages the releases for Bitwarden Client.

However, I have fixed the bug in the automation which prevents the automatic updates of Bitwarden 👍🏻

**Comment by ppvnf** [comment]
> You can create a feature request at https://github.com/bitwarden/clients/issues, so it may get the attention of the team who manages the releases for Bitwarden Client.
> 
> However, I have fixed the bug in the automation which prevents the automatic updates of Bitwarden 👍🏻

Thanks. I agree it's probably better to create a request at Github to get the attention of the devs. But since you have fixed the automation, is there any advantage of having them use winget-releaser?

**Comment by vedantmgoyal9** [comment]
Yes, there are several reasons for it:
- Sometimes automation may go offline for maintenance, hence it is better to use GitHub Action. It is also easier to maintain and implement new features in the action. All apps use the latest manifest schema and fields. <br/>
Automation is generally preferred for non-GitHub packages (meaning: software which are hosted on GitHub) that cannot take advantage of the GitHub Action.
 
- Since all GitHub API requests are authenticated with my account, using action distrubutes the amount of traffic on GitHub. The action is triggered automatically on releases, so we don't need to fetch APIs or scrape webpages to check for updates periodically, and PRs are created with the software's developer account.

- Microsoft prefers publishers managing releases for their apps themselves instead of a third party. It isn't a hard-and-fast rule, note the word "prefers" here.

**Comment by vedantmgoyal9** [comment]
I'm re-opening this, and when you've created an issue at bitwarden's repo, mention it here so that I can track its status and outcome.

**Comment by ppvnf** [comment]
> I'm re-opening this, and when you've created an issue at bitwarden's repo, mention it here so that I can track its status and outcome.

https://github.com/bitwarden/clients/issues/3816
